[package]
name = "intersections"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
plotters = "0.3"
chrono = "0.4.41"
